### ISSUE TITLE
Questions about your project

### ISSUE THREAD

**Issue by CangeJeremy** [DevinThomas185/F1-Strategy-Analysis#1]
Hello there !

First of all, i'm not a CPP dev. I'm basically a PHP dev currently learning .NET and exploring C / CPP to get more knowledge of these languages.

I jumped in your code to see how you work and, even if i'm not a CPP dev, i feel like you made a strong software here.

I wanted to ask :

Do you plan to release a compiled version of your project ?

Is there any way people like me could contribute ? (Not especially for the CPP part but if you need something else...)

Do you plan to write a tutorial, for a noob like me ^^", on how to compile your code (Question applies if you answer No to the first question) ? (I already tried tbh, i'm stuck when it comes to the Qt part)

Thank you for reading me even if you don't answer and keep up the good work !

**Comment by DevinThomas185** [comment]
Hi Jérémy!

Thank you very much for your interest in my project! It is really encouraging to hear your kind words!

My plan is to release a compiled version of the software in the future. However, it is currently underdeveloped and still possesses many bugs that would cause problems for users. I am currently trying to reduce the number of bugs and add new features simultaneously to make the software more stable. Later on, when this is achieved, I would provide a built executable.

I'll add writing a tutorial to my TODO list! I hadn't expected anyone to want to build the project yet but certainly I can attempt to help those who would like to run it themselves. With QT, the best way to run it would be to install the open source QTCreator found [here](http://qt.io/download-qt-installer-oss). Using this, you can clone the repo and open it as an existing project, then hit the run button to build and run the software. You'll have to change the UDP port and IP to your own ones to receive data (this will be changed in future to a menu bar input!)  Hopefully, this should work for you :)

If you manage to run and test the software, I would be very grateful if you could let me know about your experience as well as any bugs you find or any features you'd like to see. As for contributing, it's very early doors for this project so I'm currently working on it alone. However, if I manage to get far with it and expand outside of the C++ scope, I'll be sure to let you know!

Thanks once again for your kind comments!

Best wishes,
Devin
